nodeLinker: node-modules

packageExtensions:
  eslint-plugin-flowtype@*:
    peerDependenciesMeta:
      "@babel/plugin-syntax-flow":
        optional: true
      "@babel/plugin-transform-react-jsx":
        optional: true
      "@popperjs/core":
        optional: true
      "@testing-library/dom":
        optional: true
      azure-maps-control:
        optional: true
      guid-typescript:
        optional: true
      mapbox-gl:
        optional: true

yarnPath: .yarn/releases/yarn-1.22.15.cjs
