name: Trigger auto deployment for rlake-api

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'backend/Rlake.Api/**'
    - '.github/workflows/rlake-api-AutoDeployTrigger-84357d7b-fb78-4afe-aa8a-2f3137f0de26.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: rlake.azurecr.io
          username: ${{ secrets.RLAKEAPI_REGISTRY_USERNAME }}
          password: ${{ secrets.RLAKEAPI_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: rlake.azurecr.io/rlake-api:${{ github.sha }}
          file: ./backend/Rlake.Api/Dockerfile
          context: ./backend/Rlake.Api/


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.RLAKEAPI_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n rlake-api -g rlake --server rlake.azurecr.io --username  ${{ secrets.RLAKEAPI_REGISTRY_USERNAME }} --password ${{ secrets.RLAKEAPI_REGISTRY_PASSWORD }}
            az containerapp update -n rlake-api -g rlake --image rlake.azurecr.io/rlake-api:${{ github.sha }}
